---
-
 hosts: all
 tasks:
     - name: Install Python3
       become: yes
       apt: name=python3 update_cache=yes state=latest

     - name: Install Git package
       become: yes
       apt: name=git update_cache=yes state=latest
       
     - name: Creates directory
       become: yes
       file:
         path: docker
         state: directory
    
     - name: Install pip
       become: yes
       apt: name=python3-pip update_cache=yes state=latest
      
     - name: install docker
       become: yes
       pip: name=docker
         
     - name: Git checkout nodejs site
       become: yes
       git:
         repo: "{{ app_repo }}"
         dest: docker
     
     - name: Build Docker image from Dockerfile
       become: yes
       docker_image:
         name: web
         build:
           path: docker
           pull: yes
         source: build
         state: present
     
     - name: Running the container
       become: yes
       docker_container:
         image: web:latest
         name: webApp
         state: started
         restart_policy: always
         published_ports: "{{ app_port }}:3000"
         
        
     - name: Check if container is running
       become: yes
       shell: "docker ps"
       register: ps_output
   
     - name: Show output of docker ps
       become: yes
       debug:
         msg: "Container Output: {{ps_output.stdout}}" 
     
 handlers:
   - name: restart apache2
     become: yes
     service: name=apache2 state=restarted
