---
-
 hosts: all
 tasks:
     - name: Install Python3
       become: yes
       apt: name=python3 update_cache=yes state=latest

     - name: Install Git package
       become: yes
       apt: name=git update_cache=yes state=latest
     
     - name: Install apt-transport-https
       become: yes
       apt: name=apt-transport-https update_cache=yes state=latest
      
     - name: Install ca-certificates
       become: yes
       apt: name=ca-certificates update_cache=yes state=latest
     
     - name: Install curl
       become: yes
       apt: name=curl update_cache=yes state=latest
     
     - name: Install gnupg-agent
       become: yes
       apt: name=gnupg-agent update_cache=yes state=latest
       
     - name: Install software-properties-common
       become: yes
       apt: name=software-properties-common update_cache=yes state=latest
     
     - name: Add Docker GPG apt Key
       become: yes
       apt_key: 
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
     
     - name: Save the current Ubuntu release version into a variable
       become: yes
       shell: lsb_release -cs
       register: ubuntu_version
    
     - name: Add Docker Repository
       become: yes
       apt_repository:
         repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
         state: present
      
     - name: Install Docker
       become: yes
       apt:
         name: "docker-ce"
         state: present
         force_apt_get: "yes"
   
     - name: Test Docker with hello world example
       become: yes
       shell: "docker run hello-world"
       register: hello_world_output
   
     - name: Show output of hello word example
       become: yes
       debug:
         msg: "Container Output: {{hello_world_output.stdout}}"    
     
     - name: Create docker group
       become: yes
       group:
         name: "docker"
         state: present

     - name: Adding user ubuntu to docker group
       become: yes
       user:
         name: "ubuntu"
         groups: "docker"
         append: "yes"
       
     - name: Creates directory
       become: yes
       file:
         path: docker
         state: directory
    
     - name: Install pip
       become: yes
       apt: name=python3-pip update_cache=yes state=latest
      
     - name: install docker
       become: yes
       pip: name=docker
         
     - name: Git checkout nodejs site
       become: yes
       git:
         repo: "{{ app_repo }}"
         dest: docker
     
     - name: Build Docker image from Dockerfile
       become: yes
       docker_image:
         name: web
         build:
           path: docker
           pull: yes
         source: build
         state: present
     
     - name: Running the container
       become: yes
       docker_container:
         image: web:latest
         name: webApp
         state: started
         restart_policy: always
         exposed_ports: "49160"
         published_ports: "49160:3000"
         
        
     - name: Check if container is running
       become: yes
       shell: "docker ps"
       register: ps_output
   
     - name: Show output of docker ps
       become: yes
       debug:
         msg: "Container Output: {{ps_output.stdout}}" 
